apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-bot
  template:
    metadata:
      labels:
        app: translation-bot
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: translation-bot
          env:
            - name: GIN_MODE
              value: release
            - name: VERSION
              value: {{ .Values.version }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/var/source/config/"
              name: translation-bot-secrets
              readOnly: true
          resources:
            limits:
              memory: 500Mi
              cpu: '4'
            requests:
              memory: 250Mi
              cpu: 100m
      volumes:
        - name: translation-bot-secrets
          secret:
            secretName: "translation-bot-secrets"
      restartPolicy: Always
