apiVersion: v1
kind: Service
metadata:
  name: translation-bot
  labels:
    service: translation-bot
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: translation-bot
