apiVersion: v1
kind: Secret
metadata:
  name: translation-bot-secrets
stringData:
  config.yaml: |
    slackClientSecret: {{ .Values.secrets.slackClientSecret }}
    slackSigningSecret: {{ .Values.secrets.slackSigningKey }}
    defaultProject: {{ .Values.defaultProject }}

    projects:
    {{ range $key, $value := .Values.projects }}
      {{$key}}:
        url: {{ $value.url }}
        branch: {{ $value.branch }}
        sourceLanguage: {{ $value.sourceLanguage }}
        updateSourceFile: {{ $value.updateSourceFile }}
        preCommitAction: {{ $value.preCommitAction }}
        translationFiles:
          {{ range $lang, $file := $value.translationFiles }}
            {{ $lang }}: {{ $file }}
          {{ end }}
        gitUsername: {{ $value.gitUsername }}
        gitPassword: {{ $value.gitPassword }}
    {{ end }}