apiVersion: v1
kind: Secret
metadata:
  name: translation-bot-secrets
stringData:
  config.yaml: |
    slackClientSecret: {{ .Values.secrets.slackClientSecret }}
    slackSigningSecret: {{ .Values.secrets.slackSigningKey }}
    defaultProject: Kii

    # TODO The way helm interacts with this map will need to be refactored.
    projects:
      Kii:
        url: https://github.com/CloudMD-SSI/fusion.git
        branch: dev
        sourceLanguage: english
        translationFiles:
          english: frontend-vue/src/i18n/en-US/index.ts
          french: frontend-vue/src/i18n/fr-CA/index.ts
        gitUsername: CanadianCommander-Work
        gitPassword: {{ .Values.secrets.gitPassword }}


