apiVersion: v1
kind: Secret
metadata:
  name: translation-bot-secrets
stringData:
  config.yaml: |
    hostname: {{ .Values.hostname }}
    slackClientSecret: {{ .Values.secrets.slackClientSecret }}
    slackSigningSecret: {{ .Values.secrets.slackSigningKey }}
    defaultProject: {{ .Values.defaultProject }}

    projects:
    {{ range $key, $value := .Values.projects }}
      {{$key}}:
        url: {{ $value.url }}
        branch: {{ $value.branch }}
        sourceLanguage: {{ $value.sourceLanguage }}
        updateSourceFiles: {{ $value.updateSourceFiles }}
        preCommitAction: {{ $value.preCommitAction }}
        packs: {{ $value.packs | toYaml | nindent 2 }}
        gitUsername: {{ $value.gitUsername }}
        gitPassword: {{ $value.gitPassword }}
    {{ end }}