apiVersion: v1
kind: Secret
metadata:
  name: translation-bot-secrets
stringData:
  config.yaml: |
    slackClientSecret: {{ .Values.secrets.slackClientSecret }}
    slackSigningSecret: {{ .Values.secrets.slackSigningKey }}
