# Service account definition. Deploy this to your cluster to allow for remote deploy.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-role-binding
  namespace: translation-bot
subjects:
  - kind: ServiceAccount
    name: github
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io