hostname: translation-bot.apps.cluster.bbenetti.ca
version: <override me>
defaultProject: kii

secrets:
  slackClientSecret: <override me>
  slackSigningKey: <override me>

projects:
  kii:
    url: https://github.com/CloudMD-SSI/fusion.git
    branch: dev
    sourceLanguage: english
    updateSourceFiles: true
    preCommitAction: cd frontend-vue && yarn install && yarn run eslint --fix --ext .ts ./src/i18n/
    packs:
      - name: frontend
        translationFiles:
          english: frontend-vue/src/i18n/en-US/index.ts
          french: frontend-vue/src/i18n/fr-CA/index.ts
      - name: backend
        translationFiles:
          english: backend/lib/core/src/main/resources/locales_en.properties
          french: backend/lib/core/src/main/resources/locales_fr.properties
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>

  keycloak:
    url: https://github.com/CloudMD-SSI/fusion-keycloak.git
    branch: main
    sourceLanguage: english
    updateSourceFiles: true
    packs:
      - name: CloudMD Theme Email
        translationFiles:
          english: themes/cloudmd/email/messages/messages_en.properties
          french: themes/cloudmd/email/messages/messages_fr.properties
      - name: CloudMD Theme Login
        translationFiles:
          english: themes/cloudmd/login/messages/messages_en.properties
          french: themes/cloudmd/login/messages/messages_en.properties
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>

  snap:
    url: https://github.com/CloudMD-SSI/snapclarity.git
    branch: dev
    sourceLanguage: english
    updateSourceFiles: true
    preCommitAction: cd b2b-patient-onboarding && yarn install && yarn run eslint --fix --ext .js ./src/locales/
    packs:
      - name: frontend
        translationFiles:
          english: b2b-patient-onboarding/src/locales/en.js
          french: b2b-patient-onboarding/src/locales/fr-CA.js
      - name: backend
        translationFiles:
          french: locales/fr-CA/translation.json
          english: locales/en/translation.json
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>

  myhealthaccess:
    url: https://github.com/CloudMD-SSI/myhealthaccess.git
    branch: dev
    sourceLanguage: english
    updateSourceFiles: true
    packs:
      - name: frontend
        translationFiles:
          english: client/src/locales/en.json
          french: client/src/locales/fr.json
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>
