hostname: translation-bot.apps.cluster.bbenetti.ca
version: <override me>
defaultProject: kii

secrets:
  slackClientSecret: <override me>
  slackSigningKey: <override me>

projects:
  kii:
    url: https://github.com/CloudMD-SSI/fusion.git
    branch: dev
    sourceLanguage: english
    updateSourceFile: false
    preCommitAction: cd frontend-vue && yarn install && yarn run eslint --fix --ext .ts ./src/i18n/
    translationFiles:
      english: frontend-vue/src/i18n/en-US/index.ts
      french: frontend-vue/src/i18n/fr-CA/index.ts
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>

  snap-frontend:
    url: https://github.com/CloudMD-SSI/snapclarity.git
    branch: dev
    sourceLanguage: english
    updateSourceFile: false
    preCommitAction: cd b2b-patient-onboarding && yarn install && yarn run eslint --fix --ext .js ./src/locales/
    translationFiles:
      english: b2b-patient-onboarding/src/locales/en.js
      french: b2b-patient-onboarding/src/locales/fr-CA.js
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>

  snap-backend:
    url: https://github.com/CloudMD-SSI/snapclarity.git
    branch: dev
    sourceLanguage: english
    updateSourceFile: false
    translationFiles:
      french: locales/fr-CA/translation.json
      english: locales/en/translation.json
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>
  myhealthaccess:
    url: https://github.com/CloudMD-SSI/myhealthaccess.git
    branch: dev
    sourceLanguage: english
    updateSourceFile: false
    translationFiles:
      english: client/src/locales/en.json
      french: client/src/locales/fr.json
    gitUsername: CloudMDServiceBot
    gitPassword: <override me>
