
hostname: translation-bot.apps.cluster.bbenetti.ca
image: ghcr.io/canadiancommander/translation-bot:latest
ingressClass: haproxy

secrets:
  slackClientSecret: <override me>
  slackSigningKey: <override me>
  gitPassword: <override me>