# Build docker images and push to a registry
name: Build Image

on:
  workflow_call:
    inputs:
      docker-file:
        description: Path to the docker file to build
        required: true
        type: string
      image-name:
        description: Full name of the image to build
        required: true
        type: string
      tag:
        description: Tag of the image
        required: true
        type: string
      registry:
        description: The registry to push the image to
        required: true
        type: string

jobs:

  build-image:
    name: Build Image
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.docker-file }}
          tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }}
          push: true