on: workflow_call

jobs:

  test:
    name: Go Test
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Unit Tests
        shell: bash
        run: go test ./...