
name: Release to production

on:
  push:
    branches: [main]

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/lib-build-image.yaml
    with:
      docker-file: ./Dockerfile
      image-name: trasnlation-bot
      tag: latest
      registry: ghcr.io/canadiancommander
  deploy:
    name: Deploy to Cluster
    uses: ./.github/workflows/lib-deploy-to-cluster.yaml
    with:
      environment: prod
      cluster-url: https://api.cluster.bbenetti.ca:8441
    secrets:
      SA_TOKEN: ${{ secrets.SA_TOKEN }}
      SLACK_SIGNING_KEY: ${{ secrets.SLACK_SIGNING_KEY }}

