
name: Release to production

on:
  push:
    branches: [main]

jobs:
  determine-tag:
    name: Determine Release Tag
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    outputs:
      tag: ${{ steps.tag-step.outputs.tag }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Determine tag
        id: tag-step
        run: echo tag=$(git rev-parse HEAD) >> $GITHUB_OUTPUT

  build-image:
    name: Build Image
    needs:
      - determine-tag
    uses: ./.github/workflows/lib-build-image.yaml
    with:
      docker-file: ./Dockerfile
      image-name: translation-bot
      tag: ${{ needs.determine-tag.outputs.tag }}
      registry: ghcr.io/canadiancommander

  deploy:
    name: Deploy to Cluster
    needs:
      - build-image
      - determine-tag
    uses: ./.github/workflows/lib-deploy-to-cluster.yaml
    with:
      environment: prod
      image-tag: ${{ needs.determine-tag.outputs.tag }}
      cluster-url: https://api.cluster.bbenetti.ca:8441
    secrets:
      SA_TOKEN: ${{ secrets.SA_TOKEN }}
      SLACK_SIGNING_KEY: ${{ secrets.SLACK_SIGNING_KEY }}
      SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
      GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

